version: '3.7'

services:
  kotlin-swarm-intelligence~test:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - gradle-cache:/root/.gradle

volumes:
  gradle-cache:
